

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://rdmishrax:rdmishrax@acharya.ugyxnws.mongodb.net/?retryWrites=true&w=majority&appName=acharya
      - SECRET_KEY=advaitfoundation
      - JWT_SECRET_KEY=advaitfoundationachryaprashant
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
